# nginx.conf
worker_processes 1;

events {
    worker_connections 1024;
}

rtmp {
    server {
        listen 1935;  # Default RTMP port

        application live {
            live on;
            # record off;  # Optionally disable recording
        }
    }
}

http {
    sendfile off;
    default_type application/octet-stream;

    server {
        listen 8080;
        server_name localhost;

        # If you want HLS playback, you can configure something like:
        location /live/ {
            types {
                application/vnd.apple.mpegurl m3u8;
                video/mp2t ts;
            }
            alias /tmp/hls/;
            add_header Cache-Control no-cache;
        }
    }
}
